---
# image
nexus_name: nexus-server
nexus_image: baselibrary/nexus
nexus_version: 3.0

# network
nexus_port: 8081

nexus_data_dir: "/var/lib/nexus"

# security
nexus_admin_user: admin
nexus_admin_pass: admin123

# branding
nexus_branding_header: ""
nexus_branding_footer: "Last provisionned {{ ansible_date_time.iso8601 }}"

# repos
nexus_repos_maven_proxy:
  - name: maven-central
    remote_url: 'http://jcenter.bintray.com/'
    layout_policy: permissive
nexus_repos_maven_hosted:
  - name: maven-releases
    version_policy: release
    write_policy: allow_once
  - name: maven-snapshot
    version_policy: snapshot
    write_policy: allow
nexus_repos_maven_group:
  - name: maven-public
    member_repos:
      - maven-releases
      - maven-snapshot
      - maven-central
