---
- name: login docker registry
  docker_login:
    registry: "{{ item }}"
    username: "{{ docker_registry_username }}"
    password: "{{ docker_registry_password }}"
    email: "{{ docker_registry_email }}"
  become: yes
  with_items:
    - https://index.docker.io/v1/
    - thoughtworks.io:5000
