---
- name: "config {{ ansible_distribution|lower }} system"
  include: "config/{{ ansible_os_family|lower }}.yml"

- name: configure system authorizedkey
  authorized_key:
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    user: root
  become: yes
