---
- name: get the script from nexus server
  uri:
    method: GET
    url: "http://10.245.6.2:8081/service/siesta/rest/v1/script/repository"
    force_basic_auth: yes
    user: "admin"
    password: "admin123"
    status_code: 200
  register: script_exist
  ignore_errors: yes


- name: submit the script to nexus server
  uri:
    method: POST
    url: "http://10.245.6.2:8081/service/siesta/rest/v1/script"
    force_basic_auth: yes
    user: "admin"
    password: "admin123"
    body: "{{ lookup('file', 'maven.json') }}"
    body_format: json
    status_code: 204
  register: nexus_script_result
  when: script_exist|failed

- name: run the script in nexus server
  uri:
    method: POST
    url: "http://10.245.6.2:8081/service/siesta/rest/v1/script/repository/run"
    force_basic_auth: yes
    user: "admin"
    password: "admin123"
    HEADER_Content-Type: "text/plain"
    body_format: raw
    status_code: 200
  register: nexus_run_result
