---
- name: start artifactory server container
  docker:
    name: "repository-server"
    image: "baselibrary/artifactory:4"
    ports:
      - "8081:8081"
    volumes:
      - "/var/lib/artifactory/etc:/var/opt/jfrog/artifactory/etc"
      - "/var/lib/artifactory/logs:/var/opt/jfrog/artifactory/logs"
      - "/var/lib/artifactory/data:/var/opt/jfrog/artifactory/data"
      - "/var/lib/artifactory/backup:/var/opt/jfrog/artifactory/backup"
    restart_policy: always
  become: yes
